"""Regulatory explainability export.

Being able to export the Pipeline Inspector trace as a formal audit
artifact matters if an SME FI needs to justify an AI-assisted decision
to a regulator (HKMA, SFC).
"""

from __future__ import annotations

from datetime import datetime, timezone


class ExplainabilityReport:
    """Generate regulator-ready explainability reports."""

    def __init__(
        self,
        query: str,
        response: str,
        agent_type: str,
        trace: list[dict],
        citations: list[str],
        confidence: float,
        model_version: str,
        user_id: str,
    ):
        self.query = query
        self.response = response
        self.agent_type = agent_type
        self.trace = trace
        self.citations = citations
        self.confidence = confidence
        self.model_version = model_version
        self.user_id = user_id

    def generate(self) -> str:
        """Generate a Markdown explainability report."""
        now = datetime.now(timezone.utc).strftime("%Y-%m-%d %H:%M UTC")
        lines = [
            "# AI System Explainability Report",
            "",
            f"**Generated:** {now}",
            f"**System:** PE AI Engineering Portfolio",
            f"**Model:** {self.model_version}",
            f"**User:** {self.user_id}",
            "",
            "---",
            "",
            "## Query",
            f"\"{self.query}\"",
            "",
            "## Response",
            self.response[:2000],
            "",
            f"**Agent Type:** {self.agent_type}",
            f"**Confidence Score:** {self.confidence:.1%}",
            "",
        ]

        # Pipeline execution
        if self.trace:
            lines.append("## Pipeline Execution")
            lines.append("")
            path = " → ".join(t.get("node", "?") for t in self.trace)
            total_ms = sum(t.get("ms", 0) for t in self.trace)
            lines.append(f"**Path:** `{path}`")
            lines.append(f"**Total Time:** {total_ms}ms")
            lines.append("")

            lines.append("### Per-Node Timing")
            lines.append("")
            lines.append("| Node | Time (ms) |")
            lines.append("|------|-----------|")
            for t in self.trace:
                lines.append(f"| {t.get('node', '?')} | {t.get('ms', 0)} |")
            lines.append("")

            # Rescue path explanation
            nodes = [t.get("node", "") for t in self.trace]
            if "verify" in nodes or "wide_search" in nodes:
                lines.append("### Rescue Path")
                lines.append("")
                lines.append(
                    "The initial answer was incomplete. The system re-examined "
                    "the sources with a focused verification prompt, then performed "
                    "a wide search across all collections before arriving at the "
                    "final answer. This indicates the initial retrieval may have "
                    "missed relevant context."
                )
                lines.append("")

        # Sources
        if self.citations:
            lines.append("## Sources Referenced")
            lines.append("")
            for i, c in enumerate(self.citations, 1):
                lines.append(f"{i}. {c}")
            lines.append("")

        # Confidence explanation
        lines.append("## Confidence Assessment")
        lines.append("")
        if self.confidence >= 0.8:
            lines.append(
                "High confidence. The answer is backed by multiple sources "
                "and followed a clean pipeline path."
            )
        elif self.confidence >= 0.5:
            lines.append(
                "Moderate confidence. Key facts should be independently verified."
            )
        else:
            lines.append(
                "Low confidence. The system required rescue-path intervention. "
                "The answer should be treated with caution and verified against "
                "primary sources."
            )
        lines.append("")

        lines.append("---")
        lines.append("*This report was generated by the PE AI system for regulatory audit purposes.*")

        return "\n".join(lines)
