"""Email draft composition: deterministic templates + optional AI polish.

compose_draft() is the single entry point. Without an LLM it builds the
email from templates over the summary metrics; with one it asks the model
to rewrite/expand the draft and falls back to the template on any error.
"""

from __future__ import annotations

import json
import re

TEMPLATE_KEYS = ("digest", "monthly", "client", "alert")
TONES = ("professional", "friendly", "formal")

_TEMPLATE_INTRO = {
    "digest": "Weekly platform digest",
    "monthly": "Monthly platform report",
    "client": "Client engagement update",
    "alert": "Compliance alert",
}

_TONE_HINTS = {
    "professional": "Concise, factual, business tone.",
    "friendly": "Warm and approachable, still professional.",
    "formal": "Highly formal, suitable for board-level recipients.",
}


def _fmt_conf(conf) -> str:
    return f"{round((conf or 0) * 100)}%"


def _summary_lines(summary: dict) -> list[str]:
    """Compact, human-readable metrics block used by template bodies."""
    lines = []
    total = summary.get("total_queries") or 0
    if total == 0:
        lines.append("No activity was recorded in this period.")
        return lines
    avg = summary.get("avg_confidence") or 0
    lines.append(f"Total queries processed: {total}")
    lines.append(f"Average confidence: {_fmt_conf(avg)}")
    agents = summary.get("agent_breakdown") or []
    if agents:
        top = max(agents, key=lambda a: a.get("count", 0))
        lines.append(f"Most-used agent: {top.get('agent')} ({top.get('count')} queries)")
    top_queries = (summary.get("top_queries") or [])[:5]
    for i, q in enumerate(top_queries, 1):
        qq = (q.get("query") or "")[:90]
        conf = _fmt_conf(q.get("confidence"))
        lines.append(f"{i}. {qq} ({conf} confidence, {q.get('agent')})")
    return lines


def _build_subject(summary: dict, template_key: str) -> str:
    label = _TEMPLATE_INTRO.get(template_key, _TEMPLATE_INTRO["digest"])
    total = summary.get("total_queries") or 0
    return (
        f"{label}: {total} queries · avg confidence "
        f"{_fmt_conf(summary.get('avg_confidence'))}"
    )


def _build_body(summary: dict, template_key: str, tone: str, instructions: str) -> str:
    label = _TEMPLATE_INTRO.get(template_key, _TEMPLATE_INTRO["digest"])
    hint = _TONE_HINTS.get(tone, _TONE_HINTS["professional"])
    lines = [f"## {label}", "", hint, ""]
    if instructions:
        lines += [f"Focus: {instructions}", ""]
    lines += ["## Summary", ""]
    lines += _summary_lines(summary)
    lines += ["", "---", "Automatically generated by the PE AI Engineering Platform."]
    return "\n".join(lines)


_COMPOSE_PROMPT = """You write a short internal email draft for a PE platform.
Current draft (markdown-lite, keep it):
---
{current}
---
Rules:
- Output ONLY JSON: {{"subject": "...", "body": "..."}}
- body uses markdown-lite: "## " section titles, "**bold**", "- " bullets, no tables.
- Keep it under 2000 characters. Preserve the metrics numbers exactly.
{extra}"""


def _default_llm():
    from src.agents.graph import _make_llm
    return _make_llm(temperature=0.4)


def _compose_with_llm(summary, template_key, tone, instructions, llm) -> dict | None:
    current = _build_body(summary, template_key, tone, instructions)
    extra = ""
    if instructions:
        extra = f"- Incorporate this focus: {instructions}\n"
    from langchain_core.messages import HumanMessage, SystemMessage

    resp = llm.invoke([
        SystemMessage(content="You format valid JSON only."),
        HumanMessage(content=_COMPOSE_PROMPT.format(current=current, extra=extra)),
    ])
    text = str(getattr(resp, "content", resp))
    m = re.search(r"\{.*\}", text, re.S)
    if not m:
        return None
    parsed = json.loads(m.group(0))
    subject = str(parsed.get("subject", "")).strip()
    body = str(parsed.get("body", "")).strip()
    if not subject or not body:
        return None
    return {"subject": subject, "body": body, "generated_by": "ai"}


def compose_draft(
    summary: dict,
    template_key: str = "digest",
    tone: str = "professional",
    instructions: str = "",
    llm=None,
) -> dict:
    """Build an email draft. Returns {'subject','body','generated_by'}."""
    if llm is None:
        try:
            llm = _default_llm()
        except Exception:
            llm = None
    if llm is not None:
        try:
            refined = _compose_with_llm(summary, template_key, tone, instructions, llm)
            if refined:
                return refined
        except Exception:
            pass  # any AI failure -> deterministic template
    body = _build_body(summary, template_key, tone, instructions)
    return {
        "subject": _build_subject(summary, template_key),
        "body": body,
        "generated_by": "template",
    }
