"""Email draft composition: deterministic templates + optional AI polish.

compose_draft() is the single entry point. Without an LLM it builds the
email from templates over the summary metrics; with one it asks the model
to rewrite/expand the draft and falls back to the template on any error.
"""

from __future__ import annotations

import json
import re

TEMPLATE_KEYS = ("digest", "monthly", "client", "alert")
TONES = ("professional", "friendly", "formal")
REPLY_INTENTS = ("acknowledge", "clarify", "compliance", "custom")

_TEMPLATE_INTRO = {
    "digest": "Weekly platform digest",
    "monthly": "Monthly platform report",
    "client": "Client engagement update",
    "alert": "Compliance alert",
}

_TONE_HINTS = {
    "professional": "Concise, factual, business tone.",
    "friendly": "Warm and approachable, still professional.",
    "formal": "Highly formal, suitable for board-level recipients.",
}


def _fmt_conf(conf) -> str:
    return f"{round((conf or 0) * 100)}%"


def _summary_lines(summary: dict) -> list[str]:
    """Compact, human-readable metrics block used by template bodies."""
    lines = []
    total = summary.get("total_queries") or 0
    if total == 0:
        lines.append("No activity was recorded in this period.")
        return lines
    avg = summary.get("avg_confidence") or 0
    lines.append(f"Total queries processed: {total}")
    lines.append(f"Average confidence: {_fmt_conf(avg)}")
    agents = summary.get("agent_breakdown") or []
    if agents:
        top = max(agents, key=lambda a: a.get("count", 0))
        lines.append(f"Most-used agent: {top.get('agent')} ({top.get('count')} queries)")
    top_queries = (summary.get("top_queries") or [])[:5]
    for i, q in enumerate(top_queries, 1):
        qq = (q.get("query") or "")[:90]
        conf = _fmt_conf(q.get("confidence"))
        lines.append(f"{i}. {qq} ({conf} confidence, {q.get('agent')})")
    return lines


def _build_subject(summary: dict, template_key: str) -> str:
    label = _TEMPLATE_INTRO.get(template_key, _TEMPLATE_INTRO["digest"])
    total = summary.get("total_queries") or 0
    return (
        f"{label}: {total} queries · avg confidence "
        f"{_fmt_conf(summary.get('avg_confidence'))}"
    )


def _build_body(summary: dict, template_key: str, tone: str, instructions: str) -> str:
    label = _TEMPLATE_INTRO.get(template_key, _TEMPLATE_INTRO["digest"])
    hint = _TONE_HINTS.get(tone, _TONE_HINTS["professional"])
    lines = [f"## {label}", "", hint, ""]
    if instructions:
        lines += [f"Focus: {instructions}", ""]
    lines += ["## Summary", ""]
    lines += _summary_lines(summary)
    lines += ["", "---", "Automatically generated by the PE AI Engineering Platform."]
    return "\n".join(lines)


_COMPOSE_PROMPT = """You write a short internal email draft for a PE platform.
Current draft (markdown-lite, keep it):
---
{current}
---
Rules:
- Output ONLY JSON: {{"subject": "...", "body": "..."}}
- body uses markdown-lite: "## " section titles, "**bold**", "- " bullets, no tables.
- Keep it under 2000 characters. Preserve the metrics numbers exactly.
{extra}"""


def _default_llm():
    from src.agents.graph import _make_llm
    return _make_llm(temperature=0.4)


def _compose_with_llm(summary, template_key, tone, instructions, llm) -> dict | None:
    current = _build_body(summary, template_key, tone, instructions)
    extra = ""
    if instructions:
        extra = f"- Incorporate this focus: {instructions}\n"
    from langchain_core.messages import HumanMessage, SystemMessage

    resp = llm.invoke([
        SystemMessage(content="You format valid JSON only."),
        HumanMessage(content=_COMPOSE_PROMPT.format(current=current, extra=extra)),
    ])
    text = str(getattr(resp, "content", resp))
    m = re.search(r"\{.*\}", text, re.S)
    if not m:
        return None
    parsed = json.loads(m.group(0))
    subject = str(parsed.get("subject", "")).strip()
    body = str(parsed.get("body", "")).strip()
    if not subject or not body:
        return None
    return {"subject": subject, "body": body, "generated_by": "ai"}


def compose_draft(
    summary: dict,
    template_key: str = "digest",
    tone: str = "professional",
    instructions: str = "",
    llm=None,
) -> dict:
    """Build an email draft. Returns {'subject','body','generated_by'}."""
    if llm is None:
        try:
            llm = _default_llm()
        except Exception:
            llm = None
    if llm is not None:
        try:
            refined = _compose_with_llm(summary, template_key, tone, instructions, llm)
            if refined:
                return refined
        except Exception:
            pass  # any AI failure -> deterministic template
    body = _build_body(summary, template_key, tone, instructions)
    return {
        "subject": _build_subject(summary, template_key),
        "body": body,
        "generated_by": "template",
    }


# ---------------------------------------------------------------------------
# Email replies (master-detail mail workspace)
# ---------------------------------------------------------------------------

_INTENT_HINTS = {
    "acknowledge": (
        "Confirm receipt and acknowledge the sender's message courteously, "
        "without committing to specific next steps."
    ),
    "clarify": (
        "Ask the sender focused, specific clarifying questions about their "
        "message so the firm can act on it."
    ),
    "compliance": (
        "Provide a compliance-focused response referencing relevant SFC "
        "guidelines and regulatory expectations where they apply."
    ),
    "custom": "Follow the extra instructions exactly.",
}


_REPLY_PROMPT = """You draft a professional email reply for a private-markets firm.
Original message:
From: {sender}
Subject: {subject}
---
{body}
---
Reply intent: {hint}
Extra instructions: {instructions}
Rules:
- Output ONLY JSON: {{"subject": "...", "body": "..."}}
- The subject should normally be "Re: {subject}".
- body uses markdown-lite: "## " section titles, "**bold**", "- " bullets, no tables.
- Keep it under 1200 characters, courteous and professional.
- Never invent facts about the sender or the firm; stay grounded in the
  original message."""


def _reply_intro(intent: str) -> str:
    return {
        "acknowledge": (
            "Thank you for your message regarding the subject below. This "
            "email confirms that we have received it and are reviewing the "
            "matter. We will revert with a fuller response shortly."
        ),
        "clarify": (
            "Thank you for your message. Before we can action it, could you "
            "kindly clarify the points below so we address the right items?"
        ),
        "compliance": (
            "Thank you for your message. We have reviewed the points raised "
            "against the relevant regulatory expectations, including applicable "
            "SFC guidelines, and the summary below reflects our position."
        ),
        "custom": "Thank you for your message.",
    }.get(intent, "Thank you for your message.")


def _reply_body_template(
    intent: str, subject: str, body: str, instructions: str
) -> str:
    lines = ["## Acknowledgment", "", _reply_intro(intent), ""]
    if intent == "clarify":
        lines += [
            "## Clarifications requested",
            "",
            "- The specific action or decision you would like us to take.",
            "- Any documents or data points we should review as part of this.",
            "- The timeframe you are working to, if applicable.",
        ]
    elif intent == "compliance":
        lines += [
            "## Compliance summary",
            "",
            "- We are reviewing the message against applicable SFC guidelines "
            "and internal compliance policies.",
            "- Any regulated activity implicated will be handled in line with "
            "the relevant conduct requirements.",
            "- A follow-up will confirm the assessment once the review completes.",
        ]
    if instructions:
        lines += ["", "## Focus", "", instructions]
    lines += ["", "---", "Generated with the Jonathan Simpson & Co. AI mail workspace."]
    return "\n".join(lines)


def compose_reply(
    sender_name: str = "",
    sender_email: str = "",
    subject: str = "",
    body: str = "",
    intent: str = "acknowledge",
    instructions: str = "",
    llm=None,
) -> dict:
    """Build a reply to an incoming email.

    Returns {'subject','body','generated_by'}. With an LLM the model writes
    the reply grounded in the original message; on any failure (or no LLM)
    a deterministic per-intent template is used.
    """
    if intent not in REPLY_INTENTS:
        intent = "acknowledge"
    hint = _INTENT_HINTS.get(intent, _INTENT_HINTS["acknowledge"])
    sender = f"{sender_name} <{sender_email}>" if sender_name else (sender_email or "unknown")
    if llm is None:
        try:
            llm = _default_llm()
        except Exception:
            llm = None
    if llm is not None:
        try:
            from langchain_core.messages import HumanMessage, SystemMessage

            resp = llm.invoke([
                SystemMessage(content="You format valid JSON only."),
                HumanMessage(
                    content=_REPLY_PROMPT.format(
                        sender=sender,
                        subject=subject or "(no subject)",
                        body=(body or "(no message body provided)")[:2000],
                        hint=hint,
                        instructions=instructions or "(none)",
                    )
                ),
            ])
            text = str(getattr(resp, "content", resp))
            m = re.search(r"\{.*\}", text, re.S)
            if m:
                parsed = json.loads(m.group(0))
                subj = str(parsed.get("subject", "")).strip()
                rep = str(parsed.get("body", "")).strip()
                if subj and rep:
                    return {"subject": subj, "body": rep, "generated_by": "ai"}
        except Exception:
            pass  # any AI failure -> deterministic template
    reply_subject = f"Re: {subject}" if subject else "Re: your message"
    return {
        "subject": reply_subject,
        "body": _reply_body_template(intent, subject, body, instructions),
        "generated_by": "template",
    }
